apiVersion: v2
name: task-manager
description: OpenShift Task Manager - Demonstrates OpenShift-specific features
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - openshift
  - task-manager
  - demo
maintainers:
  - name: OpenShift Demo
    email: demo@example.com
